version: '3.3'

services:
  app:
    image: h1ka/otus:0.1
    container_name: health-status
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: java -jar ./docker-demo.jar
    network_mode: bridge
    ports:
      - "80:8000"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "/tmp:/tmp:delegated"

